-- Drop tables if they exist
DROP TABLE IF EXISTS admin_users;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS daily_reports;

-- Create a table for storing admin user data
CREATE TABLE admin_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create a table for storing user data with roles
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_admin TINYINT(1) DEFAULT 0,
    reset_password_token VARCHAR(255),
    reset_password_expires BIGINT
);
-- Create a table for storing daily reports with more detailed fields
CREATE TABLE daily_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    job_number VARCHAR(50),
    t_and_m BOOLEAN DEFAULT FALSE,
    contract BOOLEAN DEFAULT FALSE,
    foreman VARCHAR(255),
    cell_number VARCHAR(20),
    customer VARCHAR(255),
    customer_po VARCHAR(50),
    job_site VARCHAR(255),
    job_description TEXT NOT NULL,
    job_completion VARCHAR(100),
    trucks VARCHAR(255),
    welders VARCHAR(255),
    generators VARCHAR(255),
    compressors VARCHAR(255),
    fuel VARCHAR(255),
    scaffolding VARCHAR(255),
    safety_equipment VARCHAR(255),
    miscellaneous_equipment VARCHAR(255),
    material_description TEXT,
    equipment_description TEXT,
    hours_worked DECIMAL(5,2) NOT NULL,
    employee VARCHAR(255) NOT NULL,
    straight_time DECIMAL(5,2) NOT NULL,
    double_time DECIMAL(5,2) NOT NULL,
    time_and_a_half DECIMAL(5,2) NOT NULL,
    emergency_purchases TEXT NOT NULL,
    approved_by VARCHAR(255) NOT NULL,
    shift_start_time VARCHAR(20),
    temperature_humidity TEXT,
    report_copy ENUM('white', 'yellow', 'pink'),
    manlifts_equipment VARCHAR(255),
    manlifts_fuel VARCHAR(255),
    delay_lost_time TEXT,
    employees_off TEXT,
    sub_contract TEXT,
    username VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Columns for additional employees
    employee_2_hours_worked DECIMAL(5,2),
    employee_2_name VARCHAR(255),
    employee_2_straight_time DECIMAL(5,2),
    employee_2_time_and_a_half DECIMAL(5,2),
    employee_2_double_time DECIMAL(5,2),
    employee_3_hours_worked DECIMAL(5,2),
    employee_3_name VARCHAR(255),
    employee_3_straight_time DECIMAL(5,2),
    employee_3_time_and_a_half DECIMAL(5,2),
    employee_3_double_time DECIMAL(5,2),
    employee_4_hours_worked DECIMAL(5,2),
    employee_4_name VARCHAR(255),
    employee_4_straight_time DECIMAL(5,2),
    employee_4_time_and_a_half DECIMAL(5,2),
    employee_4_double_time DECIMAL(5,2),
    employee_5_hours_worked DECIMAL(5,2),
    employee_5_name VARCHAR(255),
    employee_5_straight_time DECIMAL(5,2),
    employee_5_time_and_a_half DECIMAL(5,2),
    employee_5_double_time DECIMAL(5,2),
    employee_6_hours_worked DECIMAL(5,2),
    employee_6_name VARCHAR(255),
    employee_6_straight_time DECIMAL(5,2),
    employee_6_time_and_a_half DECIMAL(5,2),
    employee_6_double_time DECIMAL(5,2),
    employee_7_hours_worked DECIMAL(5,2),
    employee_7_name VARCHAR(255),
    employee_7_straight_time DECIMAL(5,2),
    employee_7_time_and_a_half DECIMAL(5,2),
    employee_7_double_time DECIMAL(5,2),
    employee_8_hours_worked DECIMAL(5,2),
    employee_8_name VARCHAR(255),
    employee_8_straight_time DECIMAL(5,2),
    employee_8_time_and_a_half DECIMAL(5,2),
    employee_8_double_time DECIMAL(5,2),
    employee_9_hours_worked DECIMAL(5,2),
    employee_9_name VARCHAR(255),
    employee_9_straight_time DECIMAL(5,2),
    employee_9_time_and_a_half DECIMAL(5,2),
    employee_9_double_time DECIMAL(5,2),
    employee_10_hours_worked DECIMAL(5,2),
    employee_10_name VARCHAR(255),
    employee_10_straight_time DECIMAL(5,2),
    employee_10_time_and_a_half DECIMAL(5,2),
    employee_10_double_time DECIMAL(5,2),
    employee_11_hours_worked DECIMAL(5,2),
    employee_11_name VARCHAR(255),
    employee_11_straight_time DECIMAL(5,2),
    employee_11_time_and_a_half DECIMAL(5,2),
    employee_11_double_time DECIMAL(5,2),
    employee_12_hours_worked DECIMAL(5,2),
    employee_12_name VARCHAR(255),
    employee_12_straight_time DECIMAL(5,2),
    employee_12_time_and_a_half DECIMAL(5,2),
    employee_12_double_time DECIMAL(5,2),
    employee_13_hours_worked DECIMAL(5,2),
    employee_13_name VARCHAR(255),
    employee_13_straight_time DECIMAL(5,2),
    employee_13_time_and_a_half DECIMAL(5,2),
    employee_13_double_time DECIMAL(5,2),
    employee_14_hours_worked DECIMAL(5,2),
    employee_14_name VARCHAR(255),
    employee_14_straight_time DECIMAL(5,2),
    employee_14_time_and_a_half DECIMAL(5,2),
    employee_14_double_time DECIMAL(5,2),
    employee_15_hours_worked DECIMAL(5,2),
    employee_15_name VARCHAR(255),
    employee_15_straight_time DECIMAL(5,2),
    employee_15_time_and_a_half DECIMAL(5,2),
    employee_15_double_time DECIMAL(5,2),
    employee_16_hours_worked DECIMAL(5,2),
    employee_16_name VARCHAR(255),
    employee_16_straight_time DECIMAL(5,2),
    employee_16_time_and_a_half DECIMAL(5,2),
    employee_16_double_time DECIMAL(5,2),
    employee_17_hours_worked DECIMAL(5,2),
    employee_17_name VARCHAR(255),
    employee_17_straight_time DECIMAL(5,2),
    employee_17_time_and_a_half DECIMAL(5,2),
    employee_17_double_time DECIMAL(5,2),
    employee_18_hours_worked DECIMAL(5,2),
    employee_18_name VARCHAR(255),
    employee_18_straight_time DECIMAL(5,2),
    employee_18_time_and_a_half DECIMAL(5,2),
    employee_18_double_time DECIMAL(5,2),
    employee_19_hours_worked DECIMAL(5,2),
    employee_19_name VARCHAR(255),
    employee_19_straight_time DECIMAL(5,2),
    employee_19_time_and_a_half DECIMAL(5,2),
    employee_19_double_time DECIMAL(5,2),
    employee_20_hours_worked DECIMAL(5,2),
    employee_20_name VARCHAR(255),
    employee_20_straight_time DECIMAL(5,2),
    employee_20_time_and_a_half DECIMAL(5,2),
    employee_20_double_time DECIMAL(5,2)
);
